name: github pages

on:
  repository_dispatch:
    types: [build-docs]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        run: |
          git clone https://github.com/fastaudio/fastaudio.git
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install library
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1
          cd fastaudio && pip install -e .[dev,testing]

      - name: Build docs
        run: cd fastaudio && mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./fastaudio/site/
